PJT/04_pjt/accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name = 'accounts'

urlpatterns = [
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('signup/',views.signup,name='signup'),
    path('update/',views.update,name='update'),
    path('delete/',views.delete,name='delete'),
]

PJT/04_pjt/movies/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name='movies'
urlpatterns = [
    path('',views.index,name='index'),
    path('create/',views.create,name='create'),
    path('<int:pk>/detail/',views.detail,name='detail'),
    path('<int:pk>/update/',views.update,name='update'),
    path('<int:pk>/delete/',views.delete,name='delete'),
    path('<int:pk>/comments/',views.comment_create, name='comment_create'),
]

PJT/04_pjt/mypjt/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('movies/',include('movies.urls')),
    path('<int:user_pk>/password/', views.change_password, name ='change_password'),
] + static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

PJT/04_pjt/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    pass

PJT/04_pjt/movies/models.py
from django.db import models

# Create your models here.

class Movie(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    image=models.ImageField(blank=True)

class Comment(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at =models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

PJT/04_pjt/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm,UserCreationForm
from django.contrib.auth import get_user_model
class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model =get_user_model()

class CustomUserChangeForm(UserChangeForm):
    password=None
    class Meta(UserChangeForm.Meta):
        model =get_user_model()
        fields =('email', 'first_name', 'last_name', 'username',)
        

PJT/04_pjt/movies/forms.py
from django import forms
from .models import Movie,Comment

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields ='__all__'

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

PJT/04_pjt/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm,PasswordChangeForm
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm,CustomUserChangeForm
# Create your views here.

def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    if request.method =='POST':
        form = AuthenticationForm(request,request.POST)
        if form.is_valid():
            form = auth_login(request,form.get_user())
            return redirect('movies:index')
    else:
        form= AuthenticationForm()
    context ={
        'form' : form,
    }
    return render(request,'accounts/login.html',context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('movies:index')

def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    if request.method =='POST':
        form = CustomUserCreationForm(request.POST)
        form.save()
        return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context={
        'form':form,
    }
    return render(request,'accounts/signup.html',context)

@login_required
def update(request):
    if request.method =='POST':
        form = CustomUserChangeForm(request.POST,instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context ={
        'form':form,
    }
    return render(request,'accounts/update.html',context)

@login_required
def delete(request):
    request.user.delete()
    return redirect('movies:index')

@login_required
def change_password(request,user_pk):
    if request.method =='POST':
        form = PasswordChangeForm(request.user,request.POST)
        if form.is_valid():
            user=form.save()
            update_session_auth_hash(request,user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form':form,
    }
    return render(request, 'accounts/change_password.html',context)

PJT/04_pjt/movies/views.py
from django.shortcuts import render,redirect
from .models import Movie
from .forms import MovieForm,CommentForm
# Create your views here.

def index(request):
    movies = Movie.objects.all()
    context={
        'movies':movies,
    }
    return render(request,'movies/index.html',context)

def create(request):
    if request.method =='POST':
        form =MovieForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = MovieForm()
    context={
        'form' : form
    }
    return render(request,'movies/create.html',context)

def detail(request,pk):
    movie = Movie.objects.get(pk=pk)
    comment_form=CommentForm()
    comments=movie.comment_set.all()
    context = {
        'movie' : movie,
        'comment_form':comment_form,
        'comments':comments,
    }
    return render(request,'movies/detail.html',context)

def update(request,pk):
    movie =Movie.objects.get(pk=pk)
    if request.method == 'POST':
        form =MovieForm(request.POST,request.FILES, instance=movie)
        if form.is_valid():
            form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm(instance=movie)
    context = {
        'form' : form,
        'movie':movie,
    }
    return render(request,'movies/update.html',context)

def delete(request,pk):
    if request.method =='POST':
        movie=Movie.objects.get(pk=pk)
        movie.delete()
        return redirect('movies:index')
    
def comment_create(request,pk):
    movie=Movie.objects.get(pk=pk)
    comment_form=CommentForm(request.POST)
    if comment_form.is_valid():
        comment=comment_form.save(commit=False)
        comment.movie=movie
        comment.save()
        return redirect('movies:detail', movie.pk)
    context={
        'movie':movie,
        'comment_form' : comment_form,
    }
    return render(request, 'movies/detail.html',context)

PJT/04_pjt/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
   
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url "movies:index" %}">SSAFY</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url "movies:index" %}">Index</a>
                  </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url "movies:create" %}">CREATE</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url "accounts:update" %}">회원정보수정</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url "change_password" user.pk %}">비밀번호변경</a>
                  </li>
                  <li class="nav-item">
                    <form action="{% url "accounts:logout" %}" method="post">
                      {% csrf_token %}
                      <button class='nav-link btn' type="submit">로그아웃</button>
                    </form>
                    
                  </li>
                {% else %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url "accounts:signup" %}">회원가입</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url "accounts:login" %}">로그인</a>
                  </li>
                {% endif %}
              </ul>
            </div>
          </div>
      </nav>

    <div class="mx-5">
      {% block content %}
      {% endblock content %}
    </div>
   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>