PJT/04_pjt/movies/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name='movies'
urlpatterns = [
    path('',views.index,name='index'),
    path('create/',views.create,name='create'),
    path('<int:pk>/detail/',views.detail,name='detail'),
    path('<int:pk>/update/',views.update,name='update'),
    path('<int:pk>/delete/',views.delete,name='delete'),
    path('<int:pk>/comments/',views.comment_create, name='comment_create'),
]

PJT/04_pjt/movies/models.py
from django.db import models

# Create your models here.

class Movie(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()
    image=models.ImageField(blank=True)

class Comment(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at =models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

PJT/04_pjt/movies/forms.py
from django import forms
from .models import Movie,Comment

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields ='__all__'

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

PJT/04_pjt/movies/views.py
from django.shortcuts import render,redirect
from .models import Movie
from .forms import MovieForm,CommentForm
# Create your views here.

def index(request):
    movies = Movie.objects.all()
    context={
        'movies':movies,
    }
    return render(request,'movies/index.html',context)

def create(request):
    if request.method =='POST':
        form =MovieForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = MovieForm()
    context={
        'form' : form
    }
    return render(request,'movies/create.html',context)

def detail(request,pk):
    movie = Movie.objects.get(pk=pk)
    comment_form=CommentForm()
    comments=movie.comment_set.all()
    context = {
        'movie' : movie,
        'comment_form':comment_form,
        'comments':comments,
    }
    return render(request,'movies/detail.html',context)

def update(request,pk):
    movie =Movie.objects.get(pk=pk)
    if request.method == 'POST':
        form =MovieForm(request.POST,request.FILES, instance=movie)
        if form.is_valid():
            form.save()
            return redirect('movies:detail', movie.pk)
    else:
        form = MovieForm(instance=movie)
    context = {
        'form' : form,
        'movie':movie,
    }
    return render(request,'movies/update.html',context)

def delete(request,pk):
    if request.method =='POST':
        movie=Movie.objects.get(pk=pk)
        movie.delete()
        return redirect('movies:index')
    
def comment_create(request,pk):
    movie=Movie.objects.get(pk=pk)
    comment_form=CommentForm(request.POST)
    if comment_form.is_valid():
        comment=comment_form.save(commit=False)
        comment.movie=movie
        comment.save()
        return redirect('movies:detail', movie.pk)
    context={
        'movie':movie,
        'comment_form' : comment_form,
    }
    return render(request, 'movies/detail.html',context)

PJT/04_pjt/movies/templates/movies/create.html
{% extends "base.html" %}
{% block content %}
<h1 class="display-6">Create</h1>
<form action="" method="post" enctype = 'multipart/form-data'>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="제출">

</form>
{% endblock content %}

PJT/04_pjt/movies/templates/movies/detail.html
{% extends "base.html" %}

{% block content %}
<h1 class="display-6">DETAIL PAGE</h1>
{% if movie.image %}
<img width = 20% src="{{movie.image.url}}" alt="img">
{% endif %}
<h4>{{movie.title}}</h4>
<p>{{movie.description}}</p>
<hr>
<h3>댓글 목록</h3>
<ul>
    {% for comment in comments %}
        <li>{{comment.content}}</li>
    {% endfor %}
</ul>

<hr>
<form action="{% url "movies:comment_create" movie.pk %}" method="POST">
    {% csrf_token %}
    {{comment_form}}
    <input type="submit" value="댓글 작성">
</form>
    
<hr>
<form style='display : inline-block' action="{% url "movies:update" movie.pk %}">
    <button type="submit" class="btn btn-secondary">UPDATE</button>
</form>
<form style='display : inline-block' action="{% url "movies:delete" movie.pk%}" method ='POST'>
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">DELETE</button>
</form>
<hr>
<form style='display : inline-block' action="{% url "movies:index" %}">
    <button type="submit" class="btn btn-primary">BACK</button>
</form>




{% endblock content %}

PJT/04_pjt/movies/templates/movies/index.html
{% extends "base.html" %}
{% block content %}
<h1 class="display-6">INDEX PAGE</h1>
<div class="container"></div>
<div class="row row-cols-2">
  {% for movie in movies %}
  <div class="col">
    <div class="card h-100">
    <div class="card-header">
      {{ movie.title }}
    </div>
    <div class="card-body">
      <p class="card-text">{{ movie.description }}</p>
      <a href="{% url "movies:detail" movie.pk %}" class="btn btn-primary">Detail</a>
    </div>
  </div>
  </div>
  {% endfor %}
</div>

{% endblock content %}