PJT/04_pjt/accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name = 'accounts'

urlpatterns = [
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('signup/',views.signup,name='signup'),
    path('update/',views.update,name='update'),
    path('delete/',views.delete,name='delete'),
]

PJT/04_pjt/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class User(AbstractUser):
    pass

PJT/04_pjt/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm,UserCreationForm
from django.contrib.auth import get_user_model
class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model =get_user_model()

class CustomUserChangeForm(UserChangeForm):
    password=None
    class Meta(UserChangeForm.Meta):
        model =get_user_model()
        fields =('email', 'first_name', 'last_name', 'username',)
        

PJT/04_pjt/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm,PasswordChangeForm
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm,CustomUserChangeForm
# Create your views here.

def login(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    if request.method =='POST':
        form = AuthenticationForm(request,request.POST)
        if form.is_valid():
            form = auth_login(request,form.get_user())
            return redirect('movies:index')
    else:
        form= AuthenticationForm()
    context ={
        'form' : form,
    }
    return render(request,'accounts/login.html',context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('movies:index')

def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:index')
    if request.method =='POST':
        form = CustomUserCreationForm(request.POST)
        form.save()
        return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context={
        'form':form,
    }
    return render(request,'accounts/signup.html',context)

@login_required
def update(request):
    if request.method =='POST':
        form = CustomUserChangeForm(request.POST,instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context ={
        'form':form,
    }
    return render(request,'accounts/update.html',context)

@login_required
def delete(request):
    request.user.delete()
    return redirect('movies:index')

@login_required
def change_password(request,user_pk):
    if request.method =='POST':
        form = PasswordChangeForm(request.user,request.POST)
        if form.is_valid():
            user=form.save()
            update_session_auth_hash(request,user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form':form,
    }
    return render(request, 'accounts/change_password.html',context)

PJT/04_pjt/accounts/templates/accounts/change_password.html
{% extends "base.html" %}
{% block content %}
    <h1 class="display-6">PASSWORD CHANGE</h1>
    <form action="{% url "change_password" user.pk%}" method='POST'>
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="비밀번호 변경">
    </form>
{% endblock content %}

PJT/04_pjt/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
<h1 class='display-6'>LOGIN PAGE</h1>
<hr>
<form action="{% url "accounts:login" %}" method ='POST'>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="로그인">
</form>
{% endblock content %}

PJT/04_pjt/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
<h1 class='display-6'>SIGNUP PAGE</h1>
<hr>
<form action="{% url "accounts:signup" %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="회원가입">
</form>
{% endblock content %}

PJT/04_pjt/accounts/templates/accounts/update.html
{% extends "base.html" %}
{% block content %}
    <h1 class="display-6">UPDATE PAGE</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="수정">
    </form>
    <hr>
    <form action="{% url "accounts:delete" %}" method="POST">
        {% csrf_token %}
        <input type="submit" value="회원탈퇴">
    </form>
    <form action="{% url "change_password" user.pk%}" method="post">
        {% csrf_token %}
        <input type="submit" value="비밀번호 변경">
    </form>
{% endblock content %}