PJT/05_pjt/movies/urls.py
from django.urls import path,include
from . import views
app_name='movies'
urlpatterns = [
    path('',views.index,name='index'),
    path('create/', views.create, name ='create'),
    path('<int:movie_pk>/',views.detail, name='detail'),
    path('<int:movie_pk>/comments_create/',views.comments_create, name = 'comments_create'),
    path('<int:movie_pk>/delete/', views.delete, name='delete'),
    path('<int:movie_pk>/update/',views.update , name='update'),
    path('<int:movie_pk>/<int:comment_pk>/delete/',views.comments_delete, name='comments_delete'),
]

PJT/05_pjt/movies/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Movie(models.Model):
    genre_choice = [
        ('Comedy','Comedy'),
        ('Fantasy','Fantasy'),
        ('Romance','Romance'),
    ]
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title=models.CharField(max_length=50)
    description = models.TextField()
    genre=models.CharField(max_length=50,choices=genre_choice,default = 'Comedy')
    score=models.FloatField()

class Comment(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content=models.CharField(max_length=100)

PJT/05_pjt/movies/forms.py
from django import forms
from .models import Movie,Comment

class Movieform(forms.ModelForm):
    score= forms.FloatField(max_value=5,min_value=0,step_size=0.5)
    class Meta:
        model = Movie
        fields = ('title','description','genre','score',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

PJT/05_pjt/movies/views.py
from django.shortcuts import render,redirect
from .forms import Movieform,CommentForm
from .models import Movie,Comment
from django.contrib.auth.decorators import login_required
# Create your views here.

def index(request):
    movies = Movie.objects.all()
    context ={
        'movies':movies,
    }
    return render(request, 'movies/index.html',context)

def create(request):
    if request.method =='POST':
        form = Movieform(request.POST)
        if form.is_valid():
            article =form.save(commit=False)
            article.user=request.user
            article.save()
            return redirect('movies:index')
    else:
        form = Movieform()
    context = {
        'form' : form,
    }
    return render(request, 'movies/create.html',context)

def detail(request,movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    form = CommentForm()
    comments=movie.comment_set.all()
    context={
        'movie':movie,
        'form': form,
        'comments':comments
    }
    return render(request,'movies/detail.html',context)

@login_required
def update(request,movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    comments=movie.comment_set.all()
    if request.method =='POST':
        form = Movieform(request.POST, instance=movie)
        if form.is_valid():
            form.save()
            return redirect('movies:detail', movie_pk)
    else:
        form = Movieform(instance=movie)
    context = {
        'form':form,
        'movie' : movie,
        'comments':comments
    }
    return render(request,'movies/update.html',context)


@login_required
def comments_create(request,movie_pk):
    movie = Movie.objects.get(pk=movie_pk)
    form = CommentForm(request.POST)
    if request.method =='POST':
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user=request.user
            comment.movie = movie
            comment.save()
            return redirect('movies:detail', movie_pk)
    context={
        'movie':movie,
        'form' :form,
    }
    return render(request,'movies/detail.html',context)

@login_required
def delete(request,movie_pk):
    movie= Movie.objects.get(pk=movie_pk)
    if request.method =='POST':
        movie.delete()
        return redirect('movies:index')

@login_required
def comments_delete(request,movie_pk,comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.method =='POST':
        comment.delete()
        return redirect('movies:detail', movie_pk)
    

PJT/05_pjt/movies/templates/movies/create.html
{% extends "base.html" %}
{% block content %}
<h1 class="display-6">CREATE</h1>
<form action="{% url "movies:create" %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="CREATE">
</form>
{% endblock content %}

PJT/05_pjt/movies/templates/movies/detail.html
{% extends "base.html" %}
{% block content %}
    <h1 class="display-6">Detail PAGE</h1>
    <h4>{{movie.title}}</h4>
<p>{{movie.description}}</p>
<p>장르 : {{movie.genre}}</p>
<p>평점 : {{movie.score}}</p>
<hr>
<form style='display : inline-block' action="{% url "movies:update" movie.pk %}">
    <button type="submit" class="btn btn-secondary">UPDATE</button>
</form>
<form style='display : inline-block' action="{% url "movies:delete" movie.pk%}" method ='POST'>
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">DELETE</button>
</form>
<hr>
<h3>댓글 목록</h3>
<div class="card" style="width: 100%">
    <ul class="list-group list-group-flush">
        {% for comment in comments %}
        <li class="list-group-item d-flex justify-content-between">
            {{comment.user}} - {{comment.content}}
            <form style='display : inline-block' action="{% url "movies:comments_delete" movie.pk comment.pk %}" method="post">
                {% csrf_token %}
                <input type="submit" class = 'btn btn-danger' value="DELETE">
            </form>
        </li>
        {% endfor %}
    </ul>
  </div>

<hr>
<form action="{% url "movies:comments_create" movie.pk %}" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="댓글 작성">
</form>
    
<hr>

<form style='display : inline-block' action="{% url "movies:index" %}">
    <button type="submit" class="btn btn-primary">BACK</button>
</form>
{% endblock content %}

PJT/05_pjt/movies/templates/movies/index.html
{% extends "base.html" %}
{% block content %}
<h1 class="display-6">INDEX PAGE</h1>
<div class="row row-cols-2">
    {% for movie in movies %}
    <div class="col">
      <div class="card h-100">
      <div class="card-header">
        {{ movie.title }}
      </div>
      <div class="card-body">
        <p class="card-text">{{ movie.description }}</p>
        <a href="{% url "movies:detail" movie.pk %}" class="btn btn-primary">Detail</a>
      </div>
    </div>
    </div>
    {% endfor %}
  </div>
{% endblock content %}

PJT/05_pjt/movies/templates/movies/update.html
{% extends "base.html" %}
{% block content %}
<h1 class="display-6">Update</h1>
<form action="{% url "movies:update" movie.pk %}" method="post" enctype='multipart/form-data'>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="제출">
</form>
{% endblock content %}